sudo: false
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.5.1
  - 3.5.2

cache: apt

addons:
  apt:
    sources:
    - sourceline: 'deb http://ftp.us.debian.org/debian unstable main contrib non-free'
      key_url: 'https://ftp-master.debian.org/keys/archive-key-8.asc'
    packages:
      - python-dev
      - libdwarf-dev
      - libelfg0-dev
      - libunwind8-dev

install:
  - pip install .

script:
  - py.test vmprof/ -vrs
  - py.test jitlog/ -vrs

notifications:
  irc:
    channels: "irc.freenode.org#baroque-dev"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    use_notice: true
    on_success: always
    on_failure: always

  email:
    on_success: change
    on_failure: change
